name: GTest
on:
  push:
    branches: [ Starter, Solution ]
  pull_request:
    branches: [ Starter, Solution ]
permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: prep by removal
      run: rm -f a.out
    - name: Run Install script for GTest
      run:  ./.github/workflows/install-googletest.sh
    - name: remove un-needed gtest files
      run:  rm -rf googletest
    - name: Build the project
      run: g++ Test0.cpp graph.cpp edge.cpp vertex.cpp -lgtest -lgtest_main -pthread
    - name: Run the project
      run: ./a.out

  test1:
    needs: build
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Run Install script for GTest
      run:  ./.github/workflows/install-googletest.sh
    - name: remove un-needed gtest files
      run:  rm -rf googletest
    - name: Build the project
      run: g++ Test1.cpp -lgtest -lgtest_main -pthread
    - name: Run the project
      run: ./a.out

  test2:
    needs: build
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Run Install script for GTest
      run:  ./.github/workflows/install-googletest.sh
    - name: remove un-needed gtest files
      run:  rm -rf googletest
    - name: Build the project
      run: g++ Test2.cpp -lgtest -lgtest_main -pthread
    - name: Run the project
      run: ./a.out

  test3:
    needs: build
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Run Install script for GTest
      run:  ./.github/workflows/install-googletest.sh
    - name: remove un-needed gtest files
      run:  rm -rf googletest
    - name: Build the project
      run: g++ Test3.cpp -lgtest -lgtest_main -pthread
    - name: Run the project
      run: ./a.out

  test4:
    needs: build
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Run Install script for GTest
      run:  ./.github/workflows/install-googletest.sh
    - name: remove un-needed gtest files
      run:  rm -rf googletest
    - name: Build the project
      run: g++ Test4.cpp -lgtest -lgtest_main -pthread
    - name: Run the project
      run: ./a.out

